import { MonthI, WeekI } from "@/types/types"

export const monthes:MonthI[] =[
    {
        title:'Январь',
        value:0,
        color:'lightblue'
    },
    {
        title:'Февраль',
        value:1,
        color:'lightblue'
    },
    {
        title:'Март',
        value:2,
        color:'lightblue'
    },
    {
        title:'Апрель',
        value:3,
        color:'lightblue'
    },
    {
        title:'Май',
        value:4,
        color:'lightblue'
    },
    {
        title:'Июнь',
        value:5,
        color:'lightblue'
    },
    {
        title:'Июль',
        value:6,
        color:'lightblue'
    },
    {
        title:'Август',
        value:7,
        color:'lightblue'
    },
    {
        title:'Сентябрь',
        value:8,
        color:'lightblue'
    },
    {
        title:'Октябрь',
        value:9,
        color:'lightblue'
    },
    {
        title:'Ноябрь',
        value:10,
        color:'lightblue'
    },
    {
        title:'Декабрь',
        value:11,
        color:'lightblue'
    }  
];

export const week:WeekI[]=[
    {
        title:'Понедельник',
        titleShort:'Пн.',
        value:1,
        color:'lightgray'
    },
    {
        title:'Вторник',
        titleShort:'Вт.',
        value:2,
        color:'lightgray'
    },
    {
        title:'Среда',
        titleShort:'Ср.',
        value:3,
        color:'lightgray'
    },
    {
        title:'Четверг',
        titleShort:'Чт.',
        value:4,
        color:'lightgray'
    },
    {
        title:'Пятница',
        titleShort:'Пт.',
        value:5,
        color:'lightgray'
    },
    {
        title:'Суббота',
        titleShort:'Сб.',
        value:6,
        color:'lightgray'
    },
    {
        title:'Воскересенье',
        titleShort:'Вс.',
        value:0,
        color:'lightgray'
    },
]